Vagrant.configure("2") do |config|
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/debian-73-i386-virtualbox-nocm.box"
  config.vm.box = "puppet_debian_73_i386_nocm"
  # config.vm.provision :shell, :path => "vagrant-bootstrap.sh"
  config.vm.hostname = "debian73i386nocm"
  config.vm.network "private_network", ip: "192.168.67.11"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.boot_timeout = 100

  config.vm.provider "virtualbox" do |v|
    v.name = "debian73i386nocm"
   # v.gui = true
  end


end



